
var WH = {};

NAMESPACE_SVG   = 'http://www.w3.org/2000/svg';

WH.BARRIERS_ROOT_ELEMENT_ID  = 'barriers';
WH.HUD_ROOT_ELEMENT_ID       = 'hud';
WH.MENU_ROOT_ELEMENT_ID      = 'menu';

WH.BARRIER_SPACING = 650.0;
WH.TUNNEL_RADIUS = 100;
WH.MISSILE_LENGTH = 50.0;

WH.LINE_OF_SIGHT = 1600.0;
WH.FIELD_OF_VIEW = 60.0;
WH.PROJECTION_PLANE_DISTANCE = 100;