var WHVR = {};

NAMESPACE_SVG   = 'http://www.w3.org/2000/svg';

WHVR.BARRIERS_ROOT_ELEMENT_ID  = 'barriers';
WHVR.HUD_ROOT_ELEMENT_ID       = 'hud';
WHVR.MENU_ROOT_ELEMENT_ID      = 'menu';

WHVR.BARRIER_SPACING = 650.0;
WHVR.TUNNEL_RADIUS = 100;
WHVR.MISSILE_LENGTH = 50.0;

WHVR.LINE_OF_SIGHT = 1600.0;
WHVR.FIELD_OF_VIEW = 60.0;
WHVR.PROJECTION_PLANE_DISTANCE = 100;





